dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

matrix:
  allow_failures:
    - python: "3.9"

before_install: pip install poetry coveralls
install: poetry install
script: pytest --cov properconf --cov tests .
after_success: coveralls
