dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install: pip install poetry coveralls
install: poetry install
script: pytest --cov properconf --cov tests .
after_success: coveralls
