DEFAULT_SECRETS = """# -------------------------------------------------------------------
# This is an encrypted config file in TOML language (https://toml.io)
#
# Your can safely store here credentials like API keys and such,
# and commit this file to your source version control system.
# -------------------------------------------------------------------

# foo = "bar"
"""

DEFAULT_DEVELOPMENT_SECRETS = DEFAULT_SECRETS
DEFAULT_PRODUCTION_SECRETS = DEFAULT_SECRETS + 'secret_key = "<SECRET_KEY>"\n'


DEFAULT_SHARED_CONFIG = """# -------------------------------------------------------------
# Shared config
# -------------------------------------------------------------

debug = false
"""

DEFAULT_DEVELOPMENT_CONFIG = """# -------------------------------------------------------------
# Development config
# -------------------------------------------------------------

debug = true
secret_key = "---- This is a fake secret key just for development ----"
"""

DEFAULT_PRODUCTION_CONFIG = """# -------------------------------------------------------------
# Production config
# -------------------------------------------------------------

debug = false
# secret_key = Set in secrets
"""

DEFAULT_TESTING_CONFIG = """# -------------------------------------------------------------
# Testing config
# -------------------------------------------------------------

debug = false
secret_key = "---- This is a fake secret key just for testing ----"
"""

DEFAULT_INIT = """from pathlib import Path

from properconf import ConfigDict


def load_config(env):
    root_path = Path(__file__).parent
    config = ConfigDict()
    config.load_file(root_path / "shared.toml")
    config.load_file(root_path / env / "config.toml")
    config.load_secrets(root_path / env / "secrets.enc.toml")
    return config


env = os.getenv("APP_ENV", "development")
config = load_config(env)
"""

DEFAULT_ENCRIPTED_HEADER = b"""# -------------------------------------------------------------
# -- DO NOT EDIT THIS FILE --
# -------------------------------------------------------------
# This is an autogenerated encrypted config file.
# The unencrypted version has the following keys:
#
"""
